version: '3'

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql://postgresdb:password@db:5432/dockert
    ports:
      - "80:8000"

  db:
      image: postgres:15-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5432
      environment:
        - POSTGRES_USER=postgresdb
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=dockert
      ports:
        - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
      postgres_data: 